[project]
name = "geometry-calculator-backend"
version = "2.0.0"
description = "几何计算器 后端"
#readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pywebview>=5.4",
    "sympy>=1.14.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
